### PR TITLE
boards: Add seeed_xiao_nrf52 and rename SEEED_XIAO to SEEED_XIAO_SAMD21.

### PR DESCRIPTION
**Pull request by jimmo**
Includes https://github.com/micropython/micropython-media/pull/29

### CODE REVIEW

**Comment by robert-hh** [comment]
I do not know if it matters, but the writing style of the names for the XIAO boards is different, being SEEED_XIAO_SAMD21 and seeed_xiao_nrf52. Which way should be go?

**Comment by jimmo** [comment]
There's a historical accident that the nRF boards are all lower case.

**Comment by robert-hh** [comment]
OK. It's lowercase then.

**Comment by dpgeorge** [comment]
Thank you both!

**Pull request merged**
