### PR TITLE
samd: Pictures for Adafruit Feather M4 Express and Adafruit ItsyBitsy M0 Express.

### PR DESCRIPTION
**Pull request by robert-hh**

### CODE REVIEW

**Comment by dpgeorge** [comment]
It looks like the M0/M4 are backwards: we have samd boards definitions for ADAFRUIT_FEATHER_M0_EXPRESS and ADAFRUIT_ITSYBITSY_M4_EXPRESS

**Comment by robert-hh** [comment]
These are new boards, coming with the SAMD port PR.

**Comment by robert-hh** [comment]
I made my test for the SAMD port with:
Arduino ItsyBitsy M4 Express
Arduino ItsyBitsy M0 Express
Arduino Feather M4 Express
Seeed XIAO
And will do further tests with:
Sparkfun SAMD51 Thing Plus (Using a SAMD51J20 MCU with more Flash and RAM)
AlphaFred has two more Sparkfun SAM21 boards. So we can add them as well.

**Comment by dpgeorge** [comment]
Ah, I see, these are waiting for your samd PRs at micropython repo to be merged...

**Comment by dpgeorge** [comment]
Thanks, this is now merged in 126c84aac7cd03dc5c1f5b8b60ce1eccdd48b10a through be70e195f2c522d4cec1ad38cf536229cf2ffdd9 (and I renamed `SPARKFUN_SAMD51_THING_PLUS` to include an underscore between THING and PLUS).

**Pull request closed without merging**
