### PR TITLE
Updates UM board images.

### PR DESCRIPTION
**Pull request by UnexpectedMaker**
Added missing NanoS3 image and updated the rest to latest versions.

### CODE REVIEW

**Comment by dpgeorge** [comment]
For the boards that have images that changed their filename (eg UM_FEATHERS2NEO) please either change it back to what it was, or update the `board.json` files to match.

**Comment by UnexpectedMaker** [comment]
Hmm, changing the boards.json is going to take a while to get approved right? I want to have the filenames consistent but forgot it used the json file :(
Ok, I get onto that tonight.

**Comment by dpgeorge** [comment]
> changing the boards.json is going to take a while to get approved right?

If you just change the filenames in the board.json, I can merge it straightaway.

**Comment by UnexpectedMaker** [comment]
Wicked, thanks. I'll get them done tonight.

**Comment by dpgeorge** [comment]
Done!

**Comment by UnexpectedMaker** [comment]
Thanks mate!!

**Pull request merged**
