### PR TITLE
Update board images

### PR DESCRIPTION
**Pull request by mattytrentini**
Updated Niti's #4 to use folder names consistent with the board names and with higher quality images (aiming for jpeg's between 100-200kB).

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the effort on this!

They all look very good except maybe for `boards/GENERIC_SPIRAM/espeye.jpg`: this pic is of the ESP-EYE and includes a camera, which is not going to be on a generic ESP32 board, and may get confusing for users who think this firmware is specifically for the ESP-EYE.  So I think that needs to be changed (and maybe just crop that picture to only show the top side of the PCB)?

Also, I'll need to squash these commits into one on merge, and that will leave Niti as the author of the commit.  I can put your name in the commit comment to give credit to you, is that ok?

**Comment by mattytrentini** [comment]
> They all look very good except maybe for `boards/GENERIC_SPIRAM/espeye.jpg`: this pic is of the ESP-EYE and includes a camera, which is not going to be on a generic ESP32 board, and may get confusing for users who think this firmware is specifically for the ESP-EYE. So I think that needs to be changed (and maybe just crop that picture to only show the top side of the PCB)?

I struggled to find a good-quality picture of an ESP32 (chip, not module) that had separate SPIRAM (that didn't have a more specific board definition). The ESP-EYE did satisfy that but, now that you mention it, I agree, it would confuse users. I'll look for something else!

> Also, I'll need to squash these commits into one on merge, and that will leave Niti as the author of the commit. I can put your name in the commit comment to give credit to you, is that ok?

That's fine. 👍🏻

**Comment by mattytrentini** [comment]
I replaced the image of the ESP-EYE with a TTGO T8 v1.7. It's a generic-looking ESP32 board with external PSRAM. Seems appropriate?

**Comment by dpgeorge** [comment]
Looks good!

**Comment by dpgeorge** [comment]
Squashed and merged in 0258e88471723cf657f07302885f76fdd82b35cd

**Pull request closed without merging**
